# Generated by Django 4.0.5 on 2022-07-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('statment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=2000)),
                ('A', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='A', to='contest.choice')),
                ('B', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='B', to='contest.choice')),
                ('C', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='C', to='contest.choice')),
                ('D', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='D', to='contest.choice')),
                ('answered_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_answered_users', to='members.profile')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, to='members.profile')),
                ('questions', models.ManyToManyField(related_name='all_questions', to='contest.question')),
            ],
        ),
    ]
