# Generated by Django 4.0.5 on 2022-07-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.AddField(
            model_name='contest',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='C',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='C', to='contest.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='D',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='D', to='contest.choice'),
        ),
    ]
