# Generated by Django 4.0.5 on 2022-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_rename_question_question_text_contest_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='A',
        ),
        migrations.RemoveField(
            model_name='question',
            name='B',
        ),
        migrations.RemoveField(
            model_name='question',
            name='C',
        ),
        migrations.RemoveField(
            model_name='question',
            name='D',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='contest.choice'),
        ),
    ]
