# Generated by Django 4.0.5 on 2022-07-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_profile_profile_pic'),
        ('contest', '0004_alter_question_answered_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_answered_users', to='members.profile'),
        ),
    ]
