# Generated by Django 4.0.5 on 2022-07-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_profile_profile_pic'),
        ('contest', '0007_remove_contest_questions_question_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_users',
        ),
        migrations.AddField(
            model_name='question',
            name='answered_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_answered_users', to='members.profile'),
        ),
    ]
