# Generated by Django 4.0.5 on 2022-07-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_profile_followers_alter_profile_followings'),
        ('contest', '0008_remove_question_answered_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered_users',
            field=models.ManyToManyField(blank=True, related_name='all_answered_users', to='members.profile'),
        ),
    ]
