# Generated by Django 4.0.5 on 2022-07-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_profile_followers_alter_profile_followings'),
        ('contest', '0010_question_date_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile'),
        ),
    ]
