# Generated by Django 4.0.5 on 2022-07-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_remove_result_contest_contest_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contest.result'),
        ),
    ]
