# Generated by Django 4.0.5 on 2022-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0028_remove_question_answered_users_alter_result_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.DurationField(default=None),
        ),
    ]
