# Generated by Django 4.0.5 on 2022-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0029_contest_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
