# Generated by Django 4.0.5 on 2022-07-12 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0030_alter_contest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
