# Generated by Django 4.0.5 on 2022-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0032_alter_contest_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='password',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
