# Generated by Django 4.0.5 on 2022-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0033_contest_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
