# Generated by Django 4.0.5 on 2022-07-05 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
